// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4VAWk2_Tg7JG-UvOd7RWxSCbqE_5rf0c',
    appId: '1:210418222640:web:d32442b8fe8c7b20910ff5',
    messagingSenderId: '210418222640',
    projectId: 'redux-calculator-d1044',
    authDomain: 'redux-calculator-d1044.firebaseapp.com',
    storageBucket: 'redux-calculator-d1044.appspot.com',
    measurementId: 'G-D59LHNHH1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOtt8UuMg3HFN-0sM_yqfT3sUWRMyk3qA',
    appId: '1:210418222640:android:93c6b9246906da44910ff5',
    messagingSenderId: '210418222640',
    projectId: 'redux-calculator-d1044',
    storageBucket: 'redux-calculator-d1044.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNcwolFk7N1DTXqkBJ5dKrcXXhnXzpkA4',
    appId: '1:210418222640:ios:5da2a6b06272de2b910ff5',
    messagingSenderId: '210418222640',
    projectId: 'redux-calculator-d1044',
    storageBucket: 'redux-calculator-d1044.appspot.com',
    iosClientId: '210418222640-fb7eindqm3p8n3562othj777ki4lcjrt.apps.googleusercontent.com',
    iosBundleId: 'com.reduxcalculator54.app',
  );
}
